### PR TITLE
SWJ_Sequence command uses SWD related pins when SWD mode is expected

### PR DESCRIPTION
**Pull request by vccggorski**
@adamgreig @Disasm 

This change is a NOOP for most users as `SPI{1,2}_CLK` lines are shorted together in a reference HS-Probe programmer. Unfortunately in a custom PCB setup that we've built, SPI2 related GPIOs are left disconnected as they were incorrectly assumed to be used in JTAG configuration only and irrelevant for SWD based communication.

### CODE REVIEW

**Comment by adamgreig** [comment]
The current version of this code respects the number of bits requested (which might not be a multiple of 8), but this version just rounds up to the nearest byte. Maybe pass `nbits` through to the swd code and manually write out the last few?

**Comment by vccggorski** [comment]
> The current version of this code respects the number of bits requested (which might not be a multiple of 8), but this version just rounds up to the nearest byte. Maybe pass `nbits` through to the swd code and manually write out the last few?

You're right. After experimentation I decided to switch to pure bitbanging as sudden switch from SPI to bitbanging for last non % 8 bytes of payload results in skewed, uneven clock. Figured it's better to stick to single method all the way through. What do you think? This code pretty much duplicates the JTAG `fn tms_sequence` but I'm not sure where I should put the common code

**Comment by vccggorski** [comment]
Rebased on top of the newest master

**Review by adamgreig — COMMENTED** [review]
Thanks for updating! I'm happy with this from reading over the code, but want to give it a couple of tests on hardware hopefully early next week.

**Review by adamgreig — APPROVED** [review]
OK, LGTM. I don't detect any performance or functional change.

Thanks!

bors merge

**Pull request merged**
