### PR TITLE
Add USB HS support for v1.1 hardware

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by korken89** [comment]
Hi I gave this a try, and I am not able to use the probe for flashing anymore. I am getting the following error:

```
      Config default
      Target target/thumbv7em-none-eabihf/release/person-tag-bootloader
     Erasing sectors ✔ [00:00:00] [------------------------------------------]       0B/ 62.00KB @       0B/s (eta 0s )
 Programming pages   ✔ [00:00:00] [------------------------------------------]       0B/ 61.00KB @       0B/s (eta 0s )
       Error failed to flash target/thumbv7em-none-eabihf/release/person-tag-bootloader

             Caused by:
                 0: Error while flashing
                 1: Something during memory interaction went wrong
                 2: A core architecture specific error occured
                 3: Failed to read register DRW at address 0x0000000c because: Operation timed out
                 4: Operation timed out
```

And after this has happened I get the error `Error No supported probe was found` when trying to run the command again.
Do you have any idea what might be causing this?

**Comment by korken89** [comment]
Also after this happens it is not possible to program the probe with a new firmware via the SWD until it has been power cycled.

**Comment by Disasm** [comment]
I had problems with probe-rs and v1.0 board, solved them by connecting the reset line.

**Comment by Yatekii** [comment]
Sounds like the probe is too fast now and we don't properly retry. I think the JLink has similar issues but with USB :) Our retry policy is crap to be not too harsh :D

**Comment by Disasm** [comment]
This could also be a problem with USB HS high-level protocol implementation, as I doubt it's implemented correctly. Unfortunately, I'm on vacation right now and can't debug this. Will be back in a week!

**Comment by korken89** [comment]
@Disasm Don't sweat it! Enjoy your vacation! :D

**Comment by korken89** [comment]
DFU :heart:

**Comment by korken89** [comment]
Lets merge this, it's working well for me for a while and if we find and issue we can fix it :)

**Pull request merged**
