### PR TITLE
DFU Runtime support

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by adamgreig** [comment]
Oh, this is cool! Does the DFU support just extend to rebooting into DFU mode, and does it work with dfu-util etc? I should definitely backport the DFU part to FFP.

**Comment by adamgreig** [comment]
I guess you don't if it's working but I'd usually expect to write VTOR before jumping to the built-in bootloader - on the FFP code it's a CM0 without VTOR and instead does the ST-specific memory remap so the system memory starts at 0 and the vector table offset is done that way, but on the CM7 in the hs-probe we can write VTOR instead.

**Comment by Disasm** [comment]
@adamgreig this code only supports rebooting into "full" DFU with `dfu-util --detach`. It works on F723 without VTOR change or remap, but on other chips you may need a different jump-to-bootloader code.

**Comment by adamgreig** [comment]
Thanks, I read through the DFU spec and it all makes sense. I implemented it for FFP [here](https://github.com/adamgreig/ffp/commit/5009e73abfffbfdc091254274c59d26ce6c9cf6b), much nicer than having to use my custom software to request bootloading.

When I was doing this before, using a vendor-specific code but otherwise the same thing, I found if I didn't ACK the request before resetting the stm32, the host got upset at the USB state, so I reworked my USB stack a bit to be able to finish and acknowledge the request first, and then bootload afterwards. Does the usb stack here do the same thing or is it just not a problem with dfu?

**Comment by Disasm** [comment]
My implementation doesn't respond to the `DFU_DETACH` request, but it's ok as far as I understand the spec.

**Pull request merged**
