### PR TITLE
Fix build for latest stable rust 1.74.0

### PR DESCRIPTION
**Pull request by no111u3**
Fix build for latest stable rust, firmware burned and tested.

### CODE REVIEW

**Review by Yatekii — COMMENTED** [review]
Thanks! Why is this required? rustc should be backwards compatible?

**Review by adamgreig — APPROVED** [review]
Recentish Rust rejects writing through `&T` without an `UnsafeCell`, and detects doing so through pointer shenanigans, which is what was happening here. The PR adds an extra layer of redirection that is enough to trick rustc. Ultimately the problem is the write must be a byte wide to interact with the SPI register correctly, but the PAC only exposes 32-bit accesses, so somehow you have to make a fake `*mut u8` to write through.

```
error: assigning to `&T` is undefined behavior, consider using an `UnsafeCell`
   --> hs-probe-bsp/src/spi.rs:294:18
    |
294 |         unsafe { core::ptr::write_volatile(&self.spi.DR as *const _ as *mut u8, data) };
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
    = note: `#[deny(invalid_reference_casting)]` on by default
```

**Comment by adamgreig** [comment]
cc https://github.com/stm32-rs/stm32f7xx-hal/pull/207

**Comment by Disasm** [comment]
It might be a good idea to add a method to `RWRegister` which returns `*mut u32`, this value can be then casted to `*mut u8`/`*mut u16` without tricking the compiler.

**Comment by ithinuel** [comment]
It seems like this fix no longer works on 1.76.

**Pull request merged**
